In [2]:
import numpy as np
import pandas as pd

In [3]:
#Kaggle setup

import json

kaggle_info = {
    "username": "your_username",
    "key": "your_key"
}

with open("kaggle.json", "w") as f:
    json.dump(kaggle_info, f)

print("kaggle.json file created successfully!")

kaggle.json file created successfully!

In [4]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [5]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [6]:
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
License(s): other
Downloading imdb-dataset-of-50k-movie-reviews.zip to /content
  0% 0.00/25.7M [00:00<?, ?B/s]
100% 25.7M/25.7M [00:00<00:00, 877MB/s]

In [7]:
!ls

imdb-dataset-of-50k-movie-reviews.zip  kaggle.json  sample_data

In [8]:
!unzip imdb-dataset-of-50k-movie-reviews.zip

Archive:  imdb-dataset-of-50k-movie-reviews.zip
  inflating: IMDB Dataset.csv

In [53]:


df1 = pd.read_csv("IMDB Dataset.csv")

In [84]:
df= df1.iloc[:200]
df.shape

(200, 2)

In [85]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [86]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [87]:
df['sentiment'].value_counts()

sentiment
negative    115
positive     85
Name: count, dtype: int64

In [88]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [89]:
df.duplicated().sum()

np.int64(0)

In [90]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_758/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [91]:
df.duplicated().sum()

np.int64(0)

#basic preprocessing
tag removal, lowercase
removing stopwords, removing punctuation

In [92]:
import re
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)

In [93]:
df['review'].apply(remove_html_tags)

0      One of the other reviewers has mentioned that ...
1      A wonderful little production. The filming tec...
2      I thought this was a wonderful way to spend ti...
3      Basically there's a family where a little boy ...
4      Petter Mattei's "Love in the Time of Money" is...
                             ...
195    Phantasm ....Class. Phantasm II.....awesome. P...
196    Ludicrous. Angelic 9-year-old Annakin turns in...
197    Scotty (Grant Cramer, who would go on to star ...
198    If you keep rigid historical perspective out o...
199    The film quickly gets to a major chase scene w...
Name: review, Length: 200, dtype: object

In [94]:
df['review']=df['review'].apply(remove_html_tags)

/tmp/ipykernel_758/2404693686.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_html_tags)

In [95]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [96]:
df['review']=df['review'].str.lower()

/tmp/ipykernel_758/514805946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].str.lower()

In [97]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [98]:
import string
exclude=string.punctuation
def remove_punc1(text):
  return text.translate(str.maketrans('','',exclude))

In [99]:
df['review']=df['review'].apply(remove_punc1)

/tmp/ipykernel_758/1726730632.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_punc1)

In [100]:
df['review'][0]

'one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [101]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [102]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)

    x = new_text[:]
    new_text.clear()

    return " ".join(x)

In [103]:
df['review']=df['review'].apply(remove_stopwords)

/tmp/ipykernel_758/1478176011.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_stopwords)

In [104]:
df

                                                review sentiment
0    one    reviewers  mentioned   watching  1 oz e...  positive
1     wonderful little production  filming techniqu...  positive
2     thought    wonderful way  spend time    hot s...  positive
3    basically theres  family   little boy jake thi...  negative
4    petter matteis love   time  money   visually s...  positive
..                                                 ...       ...
195  phantasm class phantasm iiawesome phantasm iii...  negative
196  ludicrous angelic 9yearold annakin turns  whin...  negative
197  scotty grant cramer  would go   star   great b...  negative
198    keep rigid historical perspective     film  ...  positive
199   film quickly gets   major chase scene  ever i...  negative

[200 rows x 2 columns]

In [105]:
x= df.iloc[:,0:1]
y= df.iloc[:,-1]

In [106]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [107]:
y

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0])

In [108]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [109]:
x_train.shape

(160, 1)

Bag of words

In [110]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [111]:
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

In [112]:
x_train_bow.shape

(160, 6928)

In [113]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
gnb = GaussianNB()
bnb = BernoulliNB()
mnb = MultinomialNB()

In [114]:
gnb.fit(x_train_bow,y_train)

GaussianNB()

In [115]:
y_pred_gnb = gnb.predict(x_test_bow)
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred_gnb)

0.675

In [117]:
confusion_matrix(y_test,y_pred_gnb)

array([[18,  3],
       [10,  9]])

In [118]:
#accuracy may be less coz we have just taken the 200 rows of 50000 rows dataset

In [122]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,f1_score

accuracy = accuracy_score(y_test,y_pred_gnb)
print("Accuracy:", accuracy)

# Precision
precision = precision_score(y_test,y_pred_gnb)
print("Precision:", precision)

# Recall
recall = recall_score(y_test,y_pred_gnb)
print("Recall:", recall)
f1 = f1_score(y_test,y_pred_gnb)
print("F1:", f1)

Accuracy: 0.675
Precision: 0.75
Recall: 0.47368421052631576
F1: 0.5806451612903226

In [123]:
from sklearn.ensemble import RandomForestClassifier

In [124]:
rf = RandomForestClassifier()

In [125]:
rf.fit(x_train_bow,y_train)
y_pred=rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.625

In [126]:
#tf idf implementation

In [127]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

In [128]:
x_train_tfidf = tfidf.fit_transform(x_train['review']).toarray()
x_test_tfidf = tfidf.transform(x_test['review']).toarray()

In [129]:
rf=RandomForestClassifier()
rf.fit(x_train_tfidf,y_train)
y_pred=rf.predict(x_test_tfidf)
accuracy_score(y_test,y_pred)

0.575

In [130]:
#WORD2VEC

In [131]:
!pip install gensim
import gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 37.2 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [132]:
#now on we get pretrained dataset take time to train so now I will train on my own dataset

In [133]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [136]:
import nltk
nltk.download('punkt_tab')

from nltk.tokenize import sent_tokenize

story = []

for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [141]:
from gensim.models import Word2Vec

model = Word2Vec(

    window=10,
    min_count=2,

)

In [142]:
model.build_vocab(story)

In [143]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(93022, 122015)

In [144]:
len(model.wv.index_to_key)

3106

In [145]:
def doc_vector(doc):
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc],axis=0)

In [154]:
import numpy as np
from gensim.utils import simple_preprocess

def document_vector(doc):
    doc = simple_preprocess(doc)

    word_vectors = [model.wv[word] for word in doc if word in model.wv]

    if len(word_vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(word_vectors, axis=0)

In [155]:
 document_vector(df['review'].values[0])

array([-0.0398136 ,  0.04310245,  0.02104785, -0.00257414,  0.00677762,
       -0.09326503,  0.03343358,  0.11018255, -0.04084065, -0.03383176,
       -0.02037473, -0.09134869, -0.00600099,  0.05078901,  0.00532507,
       -0.04157427,  0.01120035, -0.04877421, -0.00317974, -0.08870636,
        0.04811786,  0.00221805,  0.03074209, -0.03636355, -0.01753982,
        0.0166602 , -0.0492827 , -0.03046811, -0.04130217,  0.01286632,
        0.05648479,  0.01559022, -0.00107734, -0.04087462, -0.02158599,
        0.05520501,  0.01226574, -0.04119077, -0.02931105, -0.0980882 ,
       -0.01293976, -0.03501531, -0.02715479,  0.00641911,  0.04751964,
       -0.01020736, -0.03328441,  0.00084013,  0.02563363,  0.04392063,
        0.01511027, -0.04595191, -0.02099917,  0.00998476, -0.03204094,
        0.03388382,  0.03225155, -0.0076675 , -0.04791627,  0.0117519 ,
        0.01487939,  0.01992427,  0.00068911,  0.01380691, -0.06585898,
        0.03269802,  0.01212163,  0.0447093 , -0.04627972,  0.06112557,
       -0.03482056,  0.0280394 ,  0.06029135, -0.00689792,  0.04253327,
        0.03593655, -0.00990406, -0.01009636, -0.04662754,  0.01828599,
       -0.02222239,  0.0164931 , -0.03811363,  0.05886076, -0.02062241,
        0.00774109,  0.02009621,  0.06153324,  0.0486737 ,  0.03730836,
        0.06472411,  0.02131347,  0.01624543,  0.00189949,  0.08798716,
        0.0434823 ,  0.03600011, -0.05316627,  0.01012569, -0.0056693 ],
      dtype=float32)

In [156]:
from tqdm import tqdm

In [160]:
X = []

for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

X = np.array(X)

X.shape

100%|██████████| 200/200 [00:00<00:00, 568.06it/s]

(200, 100)

In [161]:
#from above can say that each of 200 review get convertwd to 100 dim vector

In [163]:
X[0]

array([-0.0398136 ,  0.04310245,  0.02104785, -0.00257414,  0.00677762,
       -0.09326503,  0.03343358,  0.11018255, -0.04084065, -0.03383176,
       -0.02037473, -0.09134869, -0.00600099,  0.05078901,  0.00532507,
       -0.04157427,  0.01120035, -0.04877421, -0.00317974, -0.08870636,
        0.04811786,  0.00221805,  0.03074209, -0.03636355, -0.01753982,
        0.0166602 , -0.0492827 , -0.03046811, -0.04130217,  0.01286632,
        0.05648479,  0.01559022, -0.00107734, -0.04087462, -0.02158599,
        0.05520501,  0.01226574, -0.04119077, -0.02931105, -0.0980882 ,
       -0.01293976, -0.03501531, -0.02715479,  0.00641911,  0.04751964,
       -0.01020736, -0.03328441,  0.00084013,  0.02563363,  0.04392063,
        0.01511027, -0.04595191, -0.02099917,  0.00998476, -0.03204094,
        0.03388382,  0.03225155, -0.0076675 , -0.04791627,  0.0117519 ,
        0.01487939,  0.01992427,  0.00068911,  0.01380691, -0.06585898,
        0.03269802,  0.01212163,  0.0447093 , -0.04627972,  0.06112557,
       -0.03482056,  0.0280394 ,  0.06029135, -0.00689792,  0.04253327,
        0.03593655, -0.00990406, -0.01009636, -0.04662754,  0.01828599,
       -0.02222239,  0.0164931 , -0.03811363,  0.05886076, -0.02062241,
        0.00774109,  0.02009621,  0.06153324,  0.0486737 ,  0.03730836,
        0.06472411,  0.02131347,  0.01624543,  0.00189949,  0.08798716,
        0.0434823 ,  0.03600011, -0.05316627,  0.01012569, -0.0056693 ],
      dtype=float32)

In [164]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(df['sentiment'])

In [166]:
y

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0])

In [167]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

In [168]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [169]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)

0.55